version: '3.8'

services:
  # Base de données MySQL
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: agrodiag_db
      MYSQL_USER: agrodiag_user
      MYSQL_PASSWORD: agrodiag_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # Redis pour Celery
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend Django
  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_NAME=agrodiag_db
      - DB_USER=agrodiag_user
      - DB_PASSWORD=agrodiag_password
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 agrodiag_backend.wsgi:application"

  # Celery Worker pour les tâches asynchrones
  celery:
    build: ./backend
    restart: always
    environment:
      - DEBUG=False
      - DB_NAME=agrodiag_db
      - DB_USER=agrodiag_user
      - DB_PASSWORD=agrodiag_password
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - media_files:/app/media
    depends_on:
      - db
      - redis
      - backend
    command: celery -A agrodiag_backend worker -l info

  # Celery Beat pour les tâches périodiques
  celery-beat:
    build: ./backend
    restart: always
    environment:
      - DEBUG=False
      - DB_NAME=agrodiag_db
      - DB_USER=agrodiag_user
      - DB_PASSWORD=agrodiag_password
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./backend:/app
      - media_files:/app/media
    depends_on:
      - db
      - redis
      - backend
    command: celery -A agrodiag_backend beat -l info

  # Frontend Vite
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

  # Nginx pour servir les fichiers statiques et proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - static_files:/var/www/static
      - media_files:/var/www/media
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data:
  redis_data:
  media_files:
  static_files:
